### ISSUE TITLE
could not find Ecto.Adapters.Postgres.Connection [in Phoenix]

### ISSUE THREAD

**Issue by arthurcolle** [ericmj/postgrex#153]
Wanted to raise the issues originally posted here: 
https://github.com/phoenixframework/phoenix/issues/1489
https://github.com/elixir-lang/ecto/issues/1211

```
[info] Running Holly.Endpoint with Cowboy using http on port 4000
[info] Application holly exited: Holly.start(:normal, []) returned an error: shutdown: failed to start child: Holly.Repo
    ** (EXIT) shutdown: failed to start child: Ecto.Adapters.Postgres
        ** (EXIT) an exception was raised:
            ** (RuntimeError) could not find Ecto.Adapters.Postgres.Connection.

Please verify you have added :postgrex as a dependency:

    {:postgrex, ">= 0.0.0"}

And remember to recompile Ecto afterwards by cleaning the current build:

    mix deps.clean ecto

                (ecto) lib/ecto/adapters/sql.ex:420: Ecto.Adapters.SQL.start_link/4
                (stdlib) supervisor.erl:343: :supervisor.do_start_child/2
                (stdlib) supervisor.erl:326: :supervisor.start_children/3
                (stdlib) supervisor.erl:292: :supervisor.init_children/2
                (stdlib) gen_server.erl:328: :gen_server.init_it/6
                (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
** (Mix) Could not start application holly: Holly.start(:normal, []) returned an error: shutdown: failed to start child: Holly.Repo
    ** (EXIT) shutdown: failed to start child: Ecto.Adapters.Postgres
        ** (EXIT) an exception was raised:
            ** (RuntimeError) could not find Ecto.Adapters.Postgres.Connection.

Please verify you have added :postgrex as a dependency:

    {:postgrex, ">= 0.0.0"}

And remember to recompile Ecto afterwards by cleaning the current build:

    mix deps.clean ecto

                (ecto) lib/ecto/adapters/sql.ex:420: Ecto.Adapters.SQL.start_link/4
                (stdlib) supervisor.erl:343: :supervisor.do_start_child/2
                (stdlib) supervisor.erl:326: :supervisor.start_children/3
                (stdlib) supervisor.erl:292: :supervisor.init_children/2
                (stdlib) gen_server.erl:328: :gen_server.init_it/6
                (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

C:\Users\arthu\Code\elixir\phoenix\holly>
```

The suggestion of using 0.11 did not solve the issue, but using 0.10 worked. 

If there is any kind of regression between 0.10 and 0.11 I wanted to raise it.

Thanks

**Comment by ericmj** [comment]
This is due to breaking changes in 0.11.0. A new release of ecto is needed that fixes the version requirement.
