### ISSUE TITLE
Large inserts cause parse errors

### ISSUE THREAD

**Issue by chrismccord** [ericmj/postgrex#189]
Trying to insert 18k records via Ecto's insert_all causes the following error:

```
** (FunctionClauseError) no function clause matching in Postgrex.Messages.parse/3
         (postgrex) lib/postgrex/messages.ex:55: Postgrex.Messages.parse(<<152, 16, 0, 0, 4, 19, 0, 0, 0, 23, 0, 0, 4, 90, 0, 0, 4, 19, 0, 0, 11, 134, 0, 0, 4, 90, 0, 0, 0, 23, 0, 0, 0, 23, 0, 0, 0, 23, 0, 0, 4, 90, 0, 0, 4, 19, 0, 0, 0, 23, ...>>, 116, 680002)
         (postgrex) lib/postgrex/protocol.ex:1030: Postgrex.Protocol.msg_decode/1
         (postgrex) lib/postgrex/protocol.ex:1008: Postgrex.Protocol.msg_recv/3
         (postgrex) lib/postgrex/protocol.ex:607: Postgrex.Protocol.describe_recv/4
    (db_connection) lib/db_connection.ex:850: DBConnection.handle/4
    (db_connection) lib/db_connection.ex:874: anonymous fn/4 in DBConnection.run_query/4
    (db_connection) lib/db_connection.ex:966: anonymous fn/4 in DBConnection.run_meter/5
    (db_connection) lib/db_connection.ex:1009: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:421: DBConnection.query/4
             (ecto) lib/ecto/adapters/sql.ex:174: Ecto.Adapters.SQL.query!/5
             (ecto) lib/ecto/adapters/sql.ex:350: Ecto.Adapters.SQL.insert_all/8
             (ecto) lib/ecto/repo/schema.ex:42: Ecto.Repo.Schema.do_insert_all/6
iex(1)> [error] GenServer #PID<0.453.0> terminating
** (DBConnection.Error) client stopped: an exception was raised:
    ** (FunctionClauseError) no function clause matching in Postgrex.Messages.parse/3
        (postgrex) lib/postgrex/messages.ex:55: Postgrex.Messages.parse(<<152, 16, 0, 0, 4, 19, 0, 0, 0, 23, 0, 0, 4, 90, 0, 0, 4, 19, 0, 0, 11, 134, 0, 0, 4, 90, 0, 0, 0, 23, 0, 0, 0, 23, 0, 0, 0, 23, 0, 0, 4, 90, 0, 0, 4, 19, 0, 0, 0, 23, ...>>, 116, 680002)
        (postgrex) lib/postgrex/protocol.ex:1030: Postgrex.Protocol.msg_decode/1
        (postgrex) lib/postgrex/protocol.ex:1008: Postgrex.Protocol.msg_recv/3
        (postgrex) lib/postgrex/protocol.ex:607: Postgrex.Protocol.describe_recv/4
        (db_connection) lib/db_connection.ex:850: DBConnection.handle/4
        (db_connection) lib/db_connection.ex:874: anonymous fn/4 in DBConnection.run_query/4
        (db_connection) lib/db_connection.ex:966: anonymous fn/4 in DBConnection.run_meter/5
        (db_connection) lib/db_connection.ex:1009: DBConnection.run_begin/3
        (db_connection) lib/db_connection.ex:421: DBConnection.query/4
        (ecto) lib/ecto/adapters/sql.ex:174: Ecto.Adapters.SQL.query!/5
        (ecto) lib/ecto/adapters/sql.ex:350: Ecto.Adapters.SQL.insert_all/8
        (ecto) lib/ecto/repo/schema.ex:42: Ecto.Repo.Schema.do_insert_all/6
        (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
        (elixir) src/elixir.erl:215: :elixir.erl_eval/3
        (elixir) src/elixir.erl:203: :elixir.eval_forms/4
        (iex) lib/iex/evaluator.ex:135: IEx.Evaluator.handle_eval/6
        (iex) lib/iex/evaluator.ex:128: IEx.Evaluator.do_eval/4
        (iex) lib/iex/evaluator.ex:108: IEx.Evaluator.eval/4
        (iex) lib/iex/evaluator.ex:27: IEx.Evaluator.loop/3
        (iex) lib/iex/evaluator.ex:18: IEx.Evaluator.init/3
    (db_connection) lib/db_connection/connection.ex:206: DBConnection.Connection.handle_cast/2
    (connection) lib/connection.ex:489: Connection.handle_call/3
    (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:stop, #Reference<0.0.1.184964>, {:function_clause, [{Postgrex.Messages, :parse, [<<152, 16, 0, 0, 4, 19, 0, 0, 0, 23, 0, 0, 4, 90, 0, 0, 4, 19, 0, 0, 11, 134, 0, 0, 4, 90, 0, 0, 0, 23, 0, 0, 0, 23, 0, 0, 0, 23, 0, 0, 4, ...>>, 116, 680002], [file: 'lib/postgrex/messages.ex', line: 55]}, {Postgrex.Protocol, :msg_decode, 1, [file: 'lib/postgrex/protocol.ex', line: 1030]}, {Postgrex.Protocol, :msg_recv, 3, [file: 'lib/postgrex/protocol.ex', line: 1008]}, {Postgrex.Protocol, :describe_recv, 4, [file: 'lib/postgrex/protocol.ex', line: 607]}, {DBConnection, :handle, 4, [file: 'lib/db_connection.ex', line: 850]}, {DBConnection, :"-run_query/4-fun-0-", 4, [file: 'lib/db_connection.ex', line: 874]}, {DBConnection, :"-run_meter/5-fun-0-", 4, [file: 'lib/db_connection.ex', line: 966]}, {DBConnection, :run_begin, 3, [file: 'lib/db_connection.ex', line: 1009]}, {DBConnection, :query, 4, [file: 'lib/db_connection.ex', line: 421]}, {Ecto.Adapters.SQL, :query!, 5, [file: 'lib/ecto/adapters/sql.ex', line: 174]}, {Ecto.Adapters.SQL, :insert_all, 8, [file: 'lib/ecto/adapters/sql.ex', line: 350]}, {Ecto.Repo.Schema, :do_insert_all, 6, [file: 'lib/ecto/repo/schema.ex', line: 42]}, {:erl_eval, :do_apply, 6, [file: 'erl_eval.erl', line: 670]}, {:elixir, :erl_eval, 3, [file: 'src/elixir.erl', line: 215]}, {:elixir, :eval_forms, 4, [file: 'src/elixir.erl', line: 203]}, {IEx.Evaluator, :handle_eval, 6, [file: 'lib/iex/evaluator.ex', line: 135]}, {IEx.Evaluator, :do_eval, 4, [file: 'lib/iex/evaluator.ex', line: 128]}, {IEx.Evaluator, :eval, 4, [file: 'lib/iex/evaluator.ex', line: 108]}, {IEx.Evaluator, :loop, 3, [file: 'lib/iex/evaluator.ex', line: 27]}, {IEx.Evaluator, :init, 3, [file: 'lib/iex/evaluator.ex', line: 18]}]}, %Postgrex.Protocol{buffer: "", connection_id: 12446, null: nil, parameters: #Reference<0.0.3.1045>, postgres: :naive, queries: 192572, sock: {:gen_tcp, #Port<0.10776>}, timeout: 15000, types: 184339}}
State: %Postgrex.Protocol{buffer: "", connection_id: 12446, null: nil, parameters: #Reference<0.0.3.1045>, postgres: :naive, queries: 192572, sock: {:gen_tcp, #Port<0.10776>}, timeout: 15000, types: 184339}
```

This was solved by chunking inserts. I'm assuming there's some hard limit in pg for commands, so it's possible postgrex could detect the issue.

**Comment by ericmj** [comment]
We can check if the query size or number of parameters exceed the protocol limits and raise an appropriate error message instead of crashing.

But it looks like this error is from parsing the response from postgres so it seems to a bug in postgrex also.

**Comment by chrismccord** [comment]
Postgres version 9.5.3

**Comment by fishcakez** [comment]
I believe @chrismccord is trying to do a query with 170,000 parameters, and if so this is what is happening:

The postgresql wire protocol only supports encoding the number of parameters as a 16 bit integer or up to 32767. When encoding 170,000 as 16 bit integer we get this: <<152,16>> = <<170_000:16>> because it gets truncated to 2 bytes, with the minimum encoded binary being <<2, 152,16>>. This causes use to send an invalid value to postgres and postgres seems to ignore that value and just use the 4-byte length of the packet as whole, and then sends us back what we want except they also suffer from the same 2-byte encoding issue: <<152,16>>.  We check both that and the 4-byte length of the packet and fail.

**Comment by ericmj** [comment]
So the fix is to add a guard clause that errors if the number of parameters exceeds 2^16 and clearly document this restriction.

**Comment by fishcakez** [comment]
Ah, we don't actually send the number of parameters at this point and we may not know them (preparing query without parameters). It is postgresql that is sending the invalid value before we get a chance to.
