### ISSUE TITLE
LISTEN/NOTIFY doesn't seem to work

### ISSUE THREAD

**Issue by adamboas** [ericmj/postgrex#191]
Postgrex.Notifications#listen seems to call through to db_connection's Connection module with {:listen, &lt;channel_name&gt;}. There is no handle_call in Connection that matches these arguments so I get the following stack trace:
```
** (EXIT) an exception was raised:
                 ** (FunctionClauseError) no function clause matching in DBConnection.Connection.handle_call/3
                     (db_connection) lib/db_connection/connection.ex:164: DBConnection.Connection.handle_call({:listen, "test_channel"}, {#PID<0.157.0>, #Reference<0.0.2.979>}, %{after_connect: nil, after_connect_timeout: 15000, after_timeout: :backoff, backoff: %DBConnection.Backoff{max: 15000, min: 200, state: {200, 5000, {:rand, {%{max: 288230376151711743, next: #Function<8.51808955/1 in :rand.mk_alg/1>, type: :exsplus, uniform: #Function<9.51808955/1 in :rand.mk_alg/1>, uniform_n: #Function<10.51808955/2 in :rand.mk_alg/1>}, [67443416274800707 | 76661729626687406]}}}, type: :rand_exp}, broker: nil, client: nil, idle_timeout: 15000, mod: Postgrex.Protocol, opts: [types: true, database: "postgres", username: "postgres", password: "postgres", hostname: "localhost"], queue: {[], []}, state: %Postgrex.Protocol{buffer: :active_once, connection_id: 7058, null: nil, parameters: #Reference<0.0.2.984>, postgres: :naive, queries: 245798, sock: {:gen_tcp, #Port<0.6128>}, timeout: 5000, types: 241706}, timer: nil})
                     (connection) lib/connection.ex:489: Connection.handle_call/3
                     (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
                     (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
                     (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```
Perhaps I am using this wrong? I actually can't see how the underlying connection could handle a listen call at all.

**Comment by ericmj** [comment]
Did you start the connection with `Postgrex.Notifications.start_link/1`? Can you show your code?

**Comment by fishcakez** [comment]
As @ericmj suggested this is calling `Postgrex.Notifications.listen/2` on a process started with `Postgrex.start_link/1` instead of `Postgrex.Notifications.start_link/1`.

**Comment by adamboas** [comment]
That was the problem. I didn't notice that Notifications was it's own gen server.Thanks for your help @ericmj .
