### ISSUE TITLE
v0.11.2 release broke `mix ecto.create`

### ISSUE THREAD

**Issue by arkadiyk** [ericmj/postgrex#206]
Fails with the following error:
```
19:13:02.039 [error] Task #PID<0.326.0> started from #PID<0.47.0> terminating
** (UndefinedFunctionError) undefined function DBConnection.query/4
    (db_connection) DBConnection.query(#PID<0.327.0>, %Postgrex.Query{columns: nil, copy_data: nil, decoders: nil, encoders: nil, name: "", null: nil, param_formats: nil, result_formats: nil, statement: "CREATE DATABASE \"app_forums_api_dev\" ENCODING 'UTF8'", types: nil}, [], [backoff_type: :stop, pool: DBConnection.Connection, database: "template1", otp_app: :app_forums_api, repo: AppForumsApi.Repo, adapter: Ecto.Adapters.Postgres, username: "postgres", password: "postgres", hostname: "localhost", pool_size: 10])
    lib/ecto/adapters/postgres.ex:201: anonymous fn/2 in Ecto.Adapters.Postgres.run_query/2
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<7.64782432/0 in Ecto.Adapters.Postgres.run_query/2>
    Args: []
```

works fine after I downgraded to 0.11.1

**Comment by josevalim** [comment]
Yes. I am releasing a new Ecto that will fix it too. :)
