### ISSUE TITLE
Postgrex.Utils.version_to_int does not support beta version numbers

### ISSUE THREAD

**Issue by troyk** [ericmj/postgrex#53]
because I've yet to upgrade my dev box pg from 9.4beta2, but I'm off to do so now.

```
** (EXIT) an exception was raised:
        ** (ArgumentError) argument error
:erlang.binary_to_integer("4beta2")
            (elixir) lib/enum.ex:977: Enum."-map/2-lc$^0/1-0-"/2
            (elixir) lib/enum.ex:977: Enum."-map/2-lc$^0/1-0-"/2
            (postgrex) lib/postgrex/utils.ex:31: Postgrex.Utils.version_to_int/1
```

**Comment by troyk** [comment]
If your interested, I could do a pull request that removes any non-alpha chars from the version number?

**Comment by ericmj** [comment]
Please do
